#!/bin/bash

echo "creating directory structure..."
mkdir -p $HOME/.plumbing.php/{etc,scripts,src,versions,tmp}
cd $HOME/.plumbing.php

echo "getting files..."
curl -o scripts/plumbing https://raw.github.com/jaz303/plumbing.php/master/scripts/plumbing
curl -o scripts/server https://raw.github.com/jaz303/plumbing.php/master/scripts/server
chmod +x scripts/server

curl -o etc/flags.dist https://raw.github.com/jaz303/plumbing.php/master/etc/flags.dist
[[ ! -f etc/flags ]] && cp etc/flags.dist etc/flags

curl -o etc/lighttpd.conf.php https://raw.github.com/jaz303/plumbing.php/master/etc/lighttpd.conf.php
[[ ! -f etc/mirror ]] && echo "www.php.net" > etc/mirror

echo "sourcing plumbing..."
source $HOME/.plumbing.php/scripts/plumbing

if [[ ! -d lighttpd ]]; then
    echo "installing lighttpd..."
    __plumbing_upgrade_lighttpd
else
    echo "lighttpd is already installed, skipping"
fi

echo
echo "*****************************"
echo "* plumbing.php is installed *"
echo "*****************************"
echo
echo "Next, add the following line to your bash.profile:"
echo '[[ -s "$HOME/.plumbing.php/scripts/plumbing" ]] && source "$HOME/.plumbing.php/scripts/plumbing"'
echo
echo "Now it's time to install some PHP:"
echo "$ plumbing install php-5.3.8"
echo
echo "Thanks for using plumbing.php!"